// Auto-generated by scripts/generate-tailwind-token-colors.mjs
// Do not edit manually.
// Token categories: colors, border, borderRadius, button, background, fontSize, spacing, boxShadow

export const tokenColors = {
  'token-gray-100': 'var(--primariMode1Gray100)',
  'token-gray-150': 'var(--primariMode1Gray150)',
  'token-gray-200': 'var(--primariMode1Gray200)',
  'token-gray-400': 'var(--primariMode1Gray400)',
  'token-gray-500': 'var(--primariMode1Gray500)',
  'token-gray-600': 'var(--primariMode1Gray600)',
  'token-gray-700': 'var(--primariMode1Gray700)',
  'token-gray-800': 'var(--primariMode1Gray800)',
  'token-gray-950': 'var(--primariMode1Gray950)',
  'token-green-100': 'var(--primariMode1Green100)',
  'token-green-200': 'var(--primariMode1Green200)',
  'token-green-300': 'var(--primariMode1Green300)',
  'token-green-400': 'var(--primariMode1Green400)',
  'token-red-100': 'var(--primariMode1Red100)',
  'token-red-50': 'var(--primariMode1Red50)',
  'token-sky-600': 'var(--primariMode1Sky600)',
  'token-tokens-light-base': 'var(--tokensLightBase)',
  'token-tokens-light-h5': 'var(--tokensLightH5)',
  'token-tokens-light-medium': 'var(--tokensLightMedium)',
  'token-tokens-light-small': 'var(--tokensLightSmall)',
  'token-yellow-300': 'var(--primariMode1Yellow300)',
} as const;

export const tokenBorder = {
  'token-border-grey-100': 'var(--tokensLightBorderBorderGrey100)',
  'token-border-grey-700': 'var(--tokensLightBorderBorderGrey700)',
} as const;

export const tokenButton = {
  'token-button-green-300': 'var(--tokensLightButtonButtonGreen300)',
  'token-button-red-100': 'var(--tokensLightButtonButtonRed100)',
} as const;

export const tokenBackground = {
  'token-background-sky-600': 'var(--tokensLightBackgroundBackgroundSky600)',
  'token-background-yellow-100': 'var(--tokensLightBackgroundBackgroundYellow100)',
} as const;
