// Auto-generated by scripts/generate-tailwind-token-colors.mjs
// Do not edit manually.
// Token categories: colors, border, borderRadius, button, background, typography, spacing, boxShadow

export const tokenColors = {
  'token-primary-mode1-blue100': 'var(--primaryMode1Blue100)',
  'token-primary-mode1-blue200': 'var(--primaryMode1Blue200)',
  'token-primary-mode1-green100': 'var(--primaryMode1Green100)',
  'token-primary-mode1-green200': 'var(--primaryMode1Green200)',
  'token-primary-mode1-red100': 'var(--primaryMode1Red100)',
  'token-primary-mode1-violet100': 'var(--primaryMode1Violet100)',
  'token-primary-mode1-yellow100': 'var(--primaryMode1Yellow100)',
} as const;

export const tokenBorder = {
} as const;

export const tokenBorderRadius = {
} as const;

export const tokenButton = {
} as const;

export const tokenBackground = {
} as const;

export const tokenTypography = {
} as const;

export const tokenSpacing = {
} as const;

export const tokenBoxShadow = {
} as const;
