// Auto-generated by scripts/generate-tailwind-token-colors.mjs
// Do not edit manually.
// Token categories: colors, sizing, border, borderRadius, button, background, typography, spacing, boxShadow

export const tokenColors = {
  'token-primary-value-blue100': 'var(--primaryValueBlue100)',
  'token-primary-value-blue200': 'var(--primaryValueBlue200)',
  'token-primary-value-green100': 'var(--primaryValueGreen100)',
  'token-primary-value-green200': 'var(--primaryValueGreen200)',
  'token-primary-value-red100': 'var(--primaryValueRed100)',
  'token-primary-value-violet100': 'var(--primaryValueViolet100)',
  'token-primary-value-yellow100': 'var(--primaryValueYellow100)',
} as const;

export const tokenSizing = {
  'token-primary-value-sizing-l': 'var(--primaryValueSizingL)',
  'token-primary-value-sizing-m': 'var(--primaryValueSizingM)',
  'token-primary-value-sizing-s': 'var(--primaryValueSizingS)',
} as const;

export const tokenBorder = {
} as const;

export const tokenBorderRadius = {
} as const;

export const tokenButton = {
} as const;

export const tokenBackground = {
} as const;

export const tokenTypography = {
} as const;

export const tokenSpacing = {
} as const;

export const tokenBoxShadow = {
} as const;
